version: 0.2
phases: 
  install:
    runtime-versions:
      # nodejs: 10 
      python: 3.8
  build:
    commands:
      - npm install time
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipelinetestingnaseer --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yaml