version: 0.2
phases: 
  install:
    runtime-versions:
      # nodejs: 10 
      python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipelinetestingnaseer --output-template-file packaged.yaml
      - aws cloudformation deploy --template-file packaged.yaml --stack-name mySafeDeployStack --capabilities CAPABILITY_IAM

artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml