version: 0.2
phases: 
  install:
    runtime-versions:
      # nodejs: 10 
      python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket codepipelinetestingnaseer --output-template-file packaged-template.yml
      - aws cloudformation deploy --template-file packaged-template.yml --stack-name GitHubToLambdaTestStack --capabilities CAPABILITY_IAM --parameter-overrides BucketName=codepipelinetestingnaseer
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
