version: 0.2
phases: 
  install:
    runtime-versions:
      python: 3.6 
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipelinetestingnaseer --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yaml