AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An example SAM template for Lambda Safe Deployments.

Resources:

  SecondFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function2.lambda_handler
      Runtime: python3.8
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test2
            Method: get
      FunctionName: 'SecondFunction'