AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Displaying the time 
Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./
      # Events:
      #   MyTimeApi:
      #     Type: Api
      #     Properties:
      #       Path: /TimeResource
      #       Method: GET
